### ISSUE TITLE
Use Enum for user roles

### ISSUE THREAD

**Issue by VladislavNikoshnov** [AlinaMoskieva/sport_cms#24]
https://github.com/AlinaMoskieva/sport_cms/blob/master/app/models/user.rb#L24

попробуй использовать перечисление для ролей пользователя?

Материалы:
- http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html

**Comment by AlinaMoskieva** [comment]
https://github.com/AlinaMoskieva/sport_cms/pull/28 , @VladislavNikoshnov )

**Comment by VladislavNikoshnov** [comment]
👍
