### ISSUE TITLE
Use Pundit to authorization purposes

### ISSUE THREAD

**Issue by VladislavNikoshnov** [AlinaMoskieva/sport_cms#25]
https://github.com/AlinaMoskieva/sport_cms/blob/master/app/controllers/admin/users_controller.rb#L4
https://github.com/AlinaMoskieva/sport_cms/blob/master/app/controllers/admin/users_controller.rb#L22

Давай попробуем применить gem Pundit для проверки прав пользователя

Материалы:
- [Pundit gem](https://github.com/elabs/pundit)

**Comment by AlinaMoskieva** [comment]
https://github.com/AlinaMoskieva/sport_cms/pull/29, @VladislavNikoshnov )

**Comment by VladislavNikoshnov** [comment]
👍
